package main

import (
	"gymondo_dz/pkg/database"
	"gymondo_dz/pkg/handlers"
	"gymondo_dz/pkg/repositories"
	"log"
	"net/http"
	"os"

	_ "gymondo_dz/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title Gymondo Subscription API
// @version 1.0
// @description API for managing gym subscriptions
// @contact.name API Support
// @contact.email support@gymondo.com
// @license.name MIT
// @host localhost:8080
// @BasePath /
// @schemes http
func main() {
	err := godotenv.Load()
	if err != nil {
		log.Fatalf("Error loading .env file")
	}

	db, err := database.NewPostgresConnection()
	if err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}

	if err := database.InitializeDB(db, false); err != nil {
		log.Fatalf("Failed to initialize database: %v", err)
	}

	productRepo := repositories.NewProductRepository(db)
	subscriptionRepo := repositories.NewSubscriptionRepository(db)

	productHandler := handlers.NewProductHandler(productRepo)
	subscriptionHandler := handlers.NewSubscriptionHandler(subscriptionRepo, productRepo)

	router := gin.Default()

	productRoutes := router.Group("/products")
	{
		productRoutes.GET("", productHandler.GetProducts)
		productRoutes.GET("/:id", productHandler.GetProduct)
	}

	subscriptionRoutes := router.Group("/subscriptions")
	{
		subscriptionRoutes.POST("/:product_id", subscriptionHandler.CreateSubscription)
		subscriptionRoutes.GET("/:id", subscriptionHandler.GetSubscription)
		subscriptionRoutes.PATCH("/:id/pause", subscriptionHandler.PauseSubscription)
		subscriptionRoutes.PATCH("/:id/unpause", subscriptionHandler.UnpauseSubscription)
		subscriptionRoutes.DELETE("/:id", subscriptionHandler.CancelSubscription)
	}

	router.GET("/health", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"status": "ok"})
	})

	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}
	log.Printf("Starting server on %s", port)
	if err := router.Run(":" + port); err != nil {
		log.Fatalf("Failed to start server: %v", err)
	}
}
